version: '1.0'

services:
  cashflow.webapi:
    image: ${DOCKER_REGISTRY-}cashflowwebapi
    build:
      context: .
      dockerfile: src/CashFlow.WebApi/Dockerfile
    depends_on: 
      - database
    ports:
      - "5001:80"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - cashflow-network
  database:
    image: mysql:latest
    container_name: mysqldbcashflow
    ports:
      - "3307:3306"
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_DATABASE: CashFlow
      MYSQL_USER: cashflow
      MYSQL_PASSWORD: cash123
      MYSQL_ROOT_PASSWORD: root
    networks:
      - cashflow-network
volumes:
  db-volume:

networks:
  cashflow-network: